### ISSUE TITLE
Sprint Meeting Agenda

### ISSUE THREAD

**Issue by PatrickRBailey** [Jopatron/KWFCI#61]
- Group programming
    -  move forward with using this time for design and bigger tasks/stuck issues
- Issues with dependency problems
    - going forward we should plan better so our issues aren't dependent on each other 
- How to attack features going forward
    - Split features amongst the team
- Deployment
    - Should we wait until our first version is done to deploy to azure?
- Outstanding Sprint Issues
    - Talk on Thursday's about sprint status
    - Leave outstanding issues in Sprint they were assigned to
- Next Sprint
    - Assign the issues for the 4/22 Sprint
    - Make sure everyone feels ok with the workload

**Comment by aaronflager** [comment]
4/19
- [ ] Make document for UX Testing assignment
- [ ] Plan what we want to show KW on Friday, assuming we can meet with them
- [ ] Polish up styling and layout of BrokerInteractions

**Comment by PatrickRBailey** [comment]
## 4/22 Agenda
-  Josh walks us through how he added edit functionality on modals
- write up assignment for Brian
- talk about outstanding issues from this week
- suggestions for changes to our process
- talk about anything in the notes from our Friday meeting that needs clarification (possible new issues)
- solidify next sprint
- make tentative plan for next 2 sprints.....possibly alpha version
