### ISSUE TITLE
Alternative to Alert Data input field

### ISSUE THREAD

**Issue by JGarnick** [Jopatron/KWFCI#66]
Currently its just an input field. To reduce the amount of input error from the user, 1 idea would be to have  Day and Week dropdown boxes that are for 1-6 days, and 1-5 weeks or something. Another Idea would be to have a calendar popup that lets them click on an actual day.

**Comment by PatrickRBailey** [comment]
My vote is datepicker calendar pop-up. I believe there is a JavaScript library for that. Or we can look into possible asp.net solutions
